name: PR checks

on:
    push:
        branches: [ "main" ]
    pull_request:

jobs:
    pr-checks:
        runs-on: ubuntu-latest
        env:
            commonGradleFlags: --parallel --stacktrace --no-configuration-cache --no-daemon

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup JDK 17 for build
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Warming up Gradle
                run: ./gradlew help $commonGradleFlags

            -   name: Run detekt
                run: ./gradlew detektAll $commonGradleFlags

            -   name: Assemble app
                run: ./gradlew :app:assembleDebug $commonGradleFlags
