name: PR checks

on:
    push:
        branches: [ "main" ]
    pull_request:

jobs:
    pr-checks:
        runs-on: ubuntu-latest
        env:
            commonGradleFlags: --parallel --stacktrace --no-configuration-cache --no-daemon

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup Reviewdog
                uses: reviewdog/action-setup@v1
                with:
                    reviewdog_version: v.0.15.0

            -   name: Setup JDK 17 for build
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Warming up Gradle
                run: ./gradlew help $commonGradleFlags

            -   name: Run detekt
                run: ./gradlew detektAll $commonGradleFlags

            -   name: Run Reviewdog for Detekt
                env:
                    REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    reviewdog \
                        -f=checkstyle \
                        -name="detekt" \
                        -reporter=github-pr-check \
                        -level="error" \
                        -filter-mode="added" \
                        <./build/reports/detekt/detekt.xml

            -   name: Assemble app
                run: ./gradlew :app:assembleDebug $commonGradleFlags
